\UTdegree
\UTlongdegree
\UTyear
\UTcopyrightlegend
\UTaddsupervisor{member}
\UTaddcosupervisor{member}
\UTaddcommittee{member}
\UTtitlepage{olddegree}{month}
\UTdediction{dedication}
\begin{UTabstract}{advisor}
\begin{UTabstract}[s]{advisors}
\end{UTabstract}
\begin{UTcommittee}
\end{UTcommittee}
